# Generated by Django 4.1 on 2022-09-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=30)),
                ('imagen', models.CharField(max_length=30)),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('pasword', models.CharField(max_length=10)),
                ('rol', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id_empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('nit', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(max_length=15)),
                ('serctor_productivo', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField(max_length=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsprint1_reto3.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=20)),
                ('telefono', models.IntegerField(max_length=15)),
                ('nombre_empresa', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField(max_length=10)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsprint1_reto3.empresa')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsprint1_reto3.usuario')),
            ],
        ),
    ]
