# Generated by Django 4.1 on 2022-09-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsprint1_reto3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nit',
            new_name='Nit',
        ),
    ]
