# Generated by Django 4.1 on 2022-09-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsprint1_reto3', '0002_rename_nit_empresa_nit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='Nit',
            new_name='nit',
        ),
    ]
