# Generated by Django 4.1 on 2022-09-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsprint1_reto3', '0004_rename_apellidos_empleado_apellidos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='Nombre',
            new_name='Nombre_empresa',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Nombre_empresa',
            field=models.CharField(max_length=40),
        ),
    ]
