# Generated by Django 4.1 on 2022-09-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsprint1_reto3', '0006_rename_pasword_usuario_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='Serctor_productivo',
            new_name='Sector_productivo',
        ),
        migrations.CreateModel(
            name='registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resgistro_ingreso', models.IntegerField(max_length=10)),
                ('Resgistro_gasto', models.IntegerField(max_length=10)),
                ('Id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsprint1_reto3.empresa')),
            ],
        ),
    ]
